version: '3.1'
services:
  stats-server:
    build: ./statistics/server
    image: stats-server
    container_name: stats-server
    ports:
      - "${STATS_SERVER_PORT}:${STATS_SERVER_PORT}"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/${STATS_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${STATS_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${STATS_DB_PASSWORD}
      - SERVER_PORT=${STATS_SERVER_PORT}

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "${STATS_DB_PORT}:${STATS_DB_PORT}"
    environment:
      - POSTGRES_USER=${STATS_DB_USERNAME}
      - POSTGRES_PASSWORD=${STATS_DB_PASSWORD}
      - POSTGRES_DB=${STATS_DB_NAME}

  #TODO: раскомментировать строки ниже после имплементации основного сервиса
  #ewm-service:
  #  ports:
  #    - "8080:8080"

  #ewm-db:
  #  image: postgres:14-alpine
